# ======================================================================
# Smida's Row Insertion Permutation Algorithm (RIPA)
# Iterative version
# ======================================================================
# Written by: SMIDA Houcine L. (2026)
# Iterative row insertion permutation algorithm for generating all permutations.
# The elements of the input array must be distinct.
# ======================================================================
'''
RIPA generates permutations progressively by inserting a new row
into the previously generated permutation array at every possible
position and filling the inserted row with the new element.
'''

# ======================================================================
# Define the input array.
# ======================================================================
Tab: list = [1, 2, 3, 4]

# ======================================================================
# Begin iterative row insertion permutation
# ======================================================================
def Smida_Permutation(E, n):
    # Base case: n = 0
    # E = [[]]: 0! = 1.
    # The only permutation is the empty permutation: [].
    if n == 0:
        E = [[]]
        print(E)
        return
    # Initialize the permutation array with the first element.
    E = [[Tab[0]]]
    # Base case: n = 1
    # E = [[Tab[0]]]: 1! = 1.
    # The only permutation contains the first element: Tab[0].
    if n == 1:
        print(E)
        return
    # ==============================================================
    # Iterative construction
    # ==============================================================
    # For each new element Tab[g], construct the next permutation
    # array by inserting a new row at every possible position and
    # filling the inserted row with Tab[g].
    for g in range(1, n):
        # F stores the complete array of permutations
        # generated at the current iteration.
        F = []
        # ==========================================================
        # Row insertion
        # ==========================================================
        # Insert a new row at every possible position.
        for i in range(g + 1):
            # Create a copy of the previously generated
            # permutation array to form the current block Bi.
            Bi = [P[:] for P in E]
            # Insert the new element at position i
            # in every row of the current permutation block.
            for P in Bi:
                P.insert(i, Tab[g])
            # Append the complete permutation block to F.
            F.extend(Bi)
        # Replace E with the complete permutation array
        # generated at the current iteration.
        E = F
    # ==============================================================
    # Display all generated permutations
    # ==============================================================
    # Display each permutation stored in the final permutation array.
    for perm in E:
        print(perm)
# ======================================================================
# End iterative row insertion permutation
# ======================================================================

# ================================================================
# Display the purpose of the program
# ================================================================
print("Smida's Row Insertion Permutation Algorithm (RIPA)")
print("Written by: SMIDA Houcine L. (2026)")

# ================================================================
# Generate and display all the permutations
# ================================================================
print("\nPermutations generated by RIPA:")
# Generate all permutations iteratively.
Smida_Permutation(Tab, len(Tab))

# ======================================================================
# End 
# ======================================================================